### ISSUE TITLE
E-Mail address gives 404

### ISSUE THREAD

**Issue by JayFoxRox** [wchargin/wchargin.github.io#1]
Clicking on the "Get my email address" link gives a 404 error.

---

**Background:**

I wanted to leave some feedback for https://blender.stackexchange.com/questions/3491/dot-matrix-display-in-cycles which can be improved in current versions of blender.

Distance between A and B can be expressed as: `distance = square_root(dot_product(a, b).value).value`

So you can avoid the custom node groups in "Distance to hole", because "Vector Math" allows dot-product, and "Math" allows "Square Root". You don't have to split into components, and it's likely better for performance, too (You could also change the radius input to squared-radius, so you can skip the "Square Root" step).

There's also a built-in "Separate XYZ" / "Combine XYZ" now. Unfortunately no vector multiply / divide yet (except for cruel hacks which are also hard to read), so a lot of the other complexity remains.

I don't have a stackexchange account, but I hope you'll improve your post with these suggestions (and maybe some new contributions of your own)

**Comment by wchargin** [comment]
Thank you! reCAPTCHA MailHide appears to have been turned down. My
apologies for the inconvenience.

You’re absolutely right about the dot product formulation. I knew much
less linear algebra then than I do now, but even then I definitely knew
the “operate on the squared distance rather than taking sqrt” trick…
I’ve got no excuse there. Thanks! :-)
